name: "UI Preview Web Container"
description: "GitHub Action for enabling build and preview applications in a web container"
inputs:
  pkg_manager:
    description: "Package manager to use"
    required: true
    default: "npm"
  build_command:
    description: "Command to build the project"
    required: true
    default: "npm run build"
  serve_command:
    description: "Command to serve the project"
    required: true
    default: "npm run start"
  base_path:
    description: "Base path of the project"
    required: false
    default: "./"
  static_path:
    description: "Path to the built static files"
    required: true
    default: "./dist"
  port:
    description: "Port to run the preview server"
    required: false
    default: "3000"
runs:
  using: "node20"
  main: "/dist/index.js"
