name: Deploy WebContainer Using pr.catshoulder.dev

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  preview-webcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: UI PR preview
        uses: sayjeyhi/pr.catshoulder.dev@v0.1.7
        with:
          pkg_manager: pnpm
          root_dir: ./example
          serve_command: pnpm start
          domain: pr.catshoulder.dev
          github_user: sayjeyhi
          github_pat: ${{ secrets.GHCR_PAT }}
          kube_config: ${{ secrets.KUBE_CONFIG }}
