on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  preview-webcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: UI PR preview
        uses: sayjeyhi/ui.pr.new@v0.1.0
        with:
          pkg_manager: bun
          serve_command: bun start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
