on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: UI PR preview
        uses: sayjeyhi/ui.pr.new@v0.1.6
        with:
          base_path: ./test
          pkg_manager: bun
          build_command: bun build
          port: 3000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
